export const REQUEST_PIZZA_SIZES = 'REQUEST_PIZZA_SIZES';
export type REQUEST_PIZZA_SIZES = typeof REQUEST_PIZZA_SIZES;

export const RECEIVE_PIZZA_SIZES = 'RECEIVE_PIZZA_SIZES';
export type RECEIVE_PIZZA_SIZES = typeof RECEIVE_PIZZA_SIZES;

export const SELECT_PIZZA_SIZE = 'SELECT_PIZZA_SIZE';
export type SELECT_PIZZA_SIZE = typeof SELECT_PIZZA_SIZE;

export const INCREMENT_TOPPING_QUANTITY = 'INCREMENT_TOPPING_QUANTITY';
export type INCREMENT_TOPPING_QUANTITY = typeof INCREMENT_TOPPING_QUANTITY;

export const DECREMENT_TOPPING_QUANTITY = 'DECREMENT_TOPPING_QUANTITY';
export type DECREMENT_TOPPING_QUANTITY = typeof DECREMENT_TOPPING_QUANTITY;

export const ADD_PIZZA = 'ADD_PIZZA';
export type ADD_PIZZA = typeof ADD_PIZZA;
