export const REQUEST_PIZZA_SIZES = 'REQUEST_PIZZA_SIZES';
export type REQUEST_PIZZA_SIZES = typeof REQUEST_PIZZA_SIZES;

export const RECEIVE_PIZZA_SIZES = 'RECEIVE_PIZZA_SIZES';
export type RECEIVE_PIZZA_SIZES = typeof RECEIVE_PIZZA_SIZES;
